name: simple

type: ruby

up:
  - ruby: 2.6.3
  - bundler

commands:
  console:
    desc: "start a console"
    run: bin/console
  run:
    desc: "start the application"
    run: bin/run
  test:
    syntax:
      argument: file
      optional: args...
    run: ruby ./test_helper.rb
