name: simple

type: ruby

up:
  - ruby: 2.6.3
  - bundler

commands:
  start:
    desc: "start the application"
    run: ruby ./src/compiler.rb
  typecheck:
    desc: "Perform type-checking"
    aliases: [tc]
    run: bundle exec srb tc
  test:
    syntax:
      argument: file
      optional: args...
    run: ruby ./test_helper.rb
